# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '3DScanDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 3DScanDemo
  pod 'StandardCyborgFusion'
  pod 'StandardCyborgUI'
  pod 'StandardCyborgNetworking'
  pod 'QCloudCOSXML/Transfer'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AlamofireImage', '~> 4.1'

end
